#!/usr/bin/env python3
"""Deterministic Mosaico game asset compiler.

The runtime consumes compact, endian-stable files and never parses PNG, JSON,
TMJ or WAV.  The resulting directory is subsequently packed by
esp_mmap_assets for zero-copy access on the device.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import struct
import wave
import zlib

from PIL import Image, ImageDraw


ATLAS_HEADER = struct.Struct("<4sHHHHII")
ATLAS_FRAME = struct.Struct("<IHHHHhh")
MAP_HEADER = struct.Struct("<4sHHHHHHIIII")
MAP_OBJECT = struct.Struct("<IhhhhI")
SOUND_HEADER = struct.Struct("<4sIHHII")
ATLAS_FLAG_BINARY_ALPHA = 1 << 0
ATLAS_FLAG_OPAQUE = 1 << 1
IMA_INDEX = (-1, -1, -1, -1, 2, 4, 6, 8,
             -1, -1, -1, -1, 2, 4, 6, 8)
IMA_STEP = (7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31,
    34, 37, 41, 45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143,
    157, 173, 190, 209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544,
    598, 658, 724, 796, 876, 963, 1060, 1166, 1282, 1411, 1552, 1707,
    1878, 2066, 2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871,
    5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635,
    13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794,
    32767)


def asset_id(name: str) -> int:
    value = 2166136261
    for byte in name.encode("utf-8"):
        value = ((value ^ byte) * 16777619) & 0xFFFFFFFF
    return value


def c_identifier(name: str) -> str:
    text = "".join(character.upper() if character.isalnum() else "_"
                   for character in name)
    return "".join(character for character in text if character.isascii()).strip("_")


def write_asset_ids(destination: Path, names: set[str], animations: list[dict]) -> None:
    lines = ["// Generated by pack_game_assets.py; do not edit.",
             "#pragma once", "#include <stdint.h>", ""]
    used: set[str] = set()
    for name in sorted(names):
        symbol = f"MOSAICO_ASSET_ID_{c_identifier(name)}"
        if not symbol.endswith("_") and symbol not in used:
            used.add(symbol)
            lines.append(f"#define {symbol} UINT32_C(0x{asset_id(name):08x})")
    for animation in animations:
        symbol = c_identifier(str(animation["name"]))
        frames = animation.get("frames", [])
        if not frames:
            raise ValueError(f"animation has no frames: {animation['name']}")
        unknown = [name for name in frames if name not in names]
        if unknown:
            raise ValueError(f"animation references unknown frame: {unknown[0]}")
        ticks = int(animation.get("frame_ticks", 1))
        if ticks <= 0:
            raise ValueError(f"animation frame_ticks must be positive: {animation['name']}")
        values = ", ".join(f"UINT32_C(0x{asset_id(name):08x})" for name in frames)
        lines.extend(["", f"static const uint32_t MOSAICO_ANIMATION_{symbol}_FRAMES[] = {{{values}}};",
                      f"#define MOSAICO_ANIMATION_{symbol}_FRAME_COUNT {len(frames)}U",
                      f"#define MOSAICO_ANIMATION_{symbol}_FRAME_TICKS {ticks}U"])
    destination.write_text("\n".join(lines) + "\n", encoding="ascii")


def _strip_connected_light_background(image: Image.Image) -> Image.Image:
    """Remove generated checkerboard while retaining enclosed white detail."""
    rgba = image.convert("RGBA")
    px = rgba.load()
    width, height = rgba.size
    seen: set[tuple[int, int]] = set()
    todo: list[tuple[int, int]] = []
    for x in range(width):
        todo.extend(((x, 0), (x, height - 1)))
    for y in range(height):
        todo.extend(((0, y), (width - 1, y)))
    while todo:
        x, y = todo.pop()
        if (x, y) in seen or x < 0 or y < 0 or x >= width or y >= height:
            continue
        seen.add((x, y))
        r, g, b, _ = px[x, y]
        if max(r, g, b) - min(r, g, b) > 15 or min(r, g, b) < 205:
            continue
        px[x, y] = (r, g, b, 0)
        todo.extend(((x - 1, y), (x + 1, y), (x, y - 1), (x, y + 1)))
    return rgba


def _rgb565_a8(image: Image.Image) -> tuple[bytes, bytes]:
    rgb = bytearray()
    alpha = bytearray()
    converted = image.convert("RGBA")
    pixels = (converted.get_flattened_data() if hasattr(converted, "get_flattened_data")
              else converted.getdata())
    for r, g, b, a in pixels:
        value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        rgb.extend(struct.pack("<H", value))
        alpha.append(a)
    return bytes(rgb), bytes(alpha)


def write_atlas(source: Path, manifest: dict, destination: Path) -> dict:
    raw = _strip_connected_light_background(Image.open(source))
    columns = int(manifest["columns"])
    rows = int(manifest["rows"])
    if columns <= 0 or rows <= 0 or raw.width < columns or raw.height < rows:
        raise ValueError("atlas grid is invalid for the source image")
    if len(manifest["frames"]) > columns * rows:
        raise ValueError("atlas frame table exceeds the declared grid")
    cell_w, cell_h = raw.width // columns, raw.height // rows
    output_cell = int(manifest.get("output_cell", 64))
    atlas = Image.new("RGBA", (columns * output_cell, rows * output_cell))
    frames = []
    ids: set[int] = set()
    for index, item in enumerate(manifest["frames"]):
        col, row = index % columns, index // columns
        crop = raw.crop((col * cell_w, row * cell_h,
                         (col + 1) * cell_w, (row + 1) * cell_h))
        resampling = getattr(Image, "Resampling", Image)
        crop.thumbnail((output_cell - 4, output_cell - 4), resampling.LANCZOS)
        x = col * output_cell + (output_cell - crop.width) // 2
        y = row * output_cell + (output_cell - crop.height) // 2
        atlas.alpha_composite(crop, (x, y))
        identifier = asset_id(item["name"])
        if identifier in ids:
            raise ValueError(f"duplicate frame id: {item['name']}")
        ids.add(identifier)
        frames.append((identifier, col * output_cell, row * output_cell,
                       output_cell, output_cell,
                       int(item.get("pivot_x", output_cell // 2)),
                       int(item.get("pivot_y", output_cell // 2))))
    alpha_mode = manifest.get("alpha_mode", "smooth")
    if alpha_mode not in {"smooth", "binary", "opaque"}:
        raise ValueError(f"unsupported alpha mode: {alpha_mode}")
    if alpha_mode == "binary":
        atlas.putalpha(atlas.getchannel("A").point(lambda value: 255 if value >= 96 else 0))
    elif alpha_mode == "opaque":
        atlas.putalpha(255)
    rgb, alpha = _rgb565_a8(atlas)
    flags = 0
    if all(value in (0, 255) for value in alpha):
        flags |= ATLAS_FLAG_BINARY_ALPHA
    if all(value == 255 for value in alpha):
        flags |= ATLAS_FLAG_OPAQUE
        alpha = b""
    header = ATLAS_HEADER.pack(b"MSA1", atlas.width, atlas.height,
                               len(frames), flags, len(rgb), len(alpha))
    body = b"".join(ATLAS_FRAME.pack(*frame) for frame in frames)
    destination.write_bytes(header + body + rgb + alpha)
    return {"file": destination.name, "type": "atlas", "bytes": destination.stat().st_size,
            "width": atlas.width, "height": atlas.height, "frames": len(frames),
            "alpha_mode": alpha_mode}


def write_terrain_atlas(destination: Path) -> dict:
    atlas = Image.new("RGBA", (96, 32), (0, 0, 0, 0))
    draw = ImageDraw.Draw(atlas)
    colors = ((12, 31, 36, 255), (29, 43, 52, 255), (17, 58, 63, 255))
    names = ("tile_grass", "tile_path", "tile_build")
    for index, color in enumerate(colors):
        x = index * 32
        draw.rectangle((x, 0, x + 31, 31), fill=color)
        for p in range(4, 32, 8):
            draw.point((x + p, (p * 3 + index * 5) % 29 + 1),
                       fill=(color[0] + 15, color[1] + 18, color[2] + 18, 255))
        if index == 1:
            draw.line((x, 3, x + 31, 3), fill=(47, 116, 122, 255), width=2)
            draw.line((x, 28, x + 31, 28), fill=(47, 116, 122, 255), width=2)
    rgb, _alpha = _rgb565_a8(atlas)
    frames = [ATLAS_FRAME.pack(asset_id(name), i * 32, 0, 32, 32, 16, 16)
              for i, name in enumerate(names)]
    destination.write_bytes(ATLAS_HEADER.pack(b"MSA1", 96, 32, 3, 0,
                                               len(rgb), 0) +
                            b"".join(frames) + rgb)
    return {"file": destination.name, "type": "atlas", "bytes": destination.stat().st_size,
            "width": 96, "height": 32, "frames": 3}


def write_tilemap(source: Path, destination: Path) -> dict:
    data = json.loads(source.read_text(encoding="utf-8"))
    if data.get("orientation") != "orthogonal" or data.get("infinite"):
        raise ValueError("only finite orthogonal Tiled maps are supported")
    width, height = int(data["width"]), int(data["height"])
    tile_w, tile_h = int(data["tilewidth"]), int(data["tileheight"])
    tile_layers = [layer for layer in data["layers"] if layer["type"] == "tilelayer"]
    object_layers = [layer for layer in data["layers"] if layer["type"] == "objectgroup"]
    layers = bytearray()
    for layer in tile_layers:
        values = layer["data"]
        if len(values) != width * height:
            raise ValueError(f"invalid layer length: {layer.get('name')}")
        if any(not isinstance(value, int) or value < 0 or value > 3 for value in values):
            raise ValueError(f"invalid tile reference: {layer.get('name')}")
        layers.extend(struct.pack(f"<{len(values)}H", *values))
    objects = bytearray()
    paths = bytearray()
    object_count = point_count = 0
    for layer in object_layers:
        for item in layer.get("objects", []):
            props = {p["name"]: p.get("value") for p in item.get("properties", [])}
            flags = int(props.get("flags", 0))
            objects.extend(MAP_OBJECT.pack(asset_id(item.get("name", "")),
                round(item.get("x", 0)), round(item.get("y", 0)),
                round(item.get("width", 0)), round(item.get("height", 0)), flags))
            object_count += 1
            polyline = item.get("polyline", [])
            for point in polyline:
                paths.extend(struct.pack("<hh", round(item.get("x", 0) + point["x"]),
                                         round(item.get("y", 0) + point["y"])))
                point_count += 1
    collision = bytearray((width * height + 7) // 8)
    for layer in tile_layers:
        if layer.get("name", "").lower() != "collision":
            continue
        for index, value in enumerate(layer["data"]):
            if value:
                collision[index // 8] |= 1 << (index & 7)
    header = MAP_HEADER.pack(b"MTM1", width, height, tile_w, tile_h,
        len(tile_layers), object_count, point_count, len(layers), len(collision),
        asset_id(data.get("tileset", "terrain.atlas")))
    destination.write_bytes(header + layers + collision + objects + paths)
    return {"file": destination.name, "type": "tilemap", "bytes": destination.stat().st_size,
            "width": width, "height": height, "layers": len(tile_layers),
            "objects": object_count, "path_points": point_count}


def write_sound(source: Path, destination: Path) -> dict:
    with wave.open(str(source), "rb") as wav:
        channels, width, rate, frames = (wav.getnchannels(), wav.getsampwidth(),
                                         wav.getframerate(), wav.getnframes())
        if width != 2:
            raise ValueError(f"{source}: only 16-bit WAV is supported")
        if wav.getcomptype() != "NONE" or channels < 1:
            raise ValueError(f"{source}: compressed or channel-less WAV is unsupported")
        samples = struct.unpack(f"<{frames * channels}h", wav.readframes(frames))
    mono = [sum(samples[i:i + channels]) // channels
            for i in range(0, len(samples), channels)]
    target_rate = 24000
    if rate != target_rate:
        count = max(1, round(len(mono) * target_rate / rate))
        mono = [mono[min(len(mono) - 1, i * rate // target_rate)] for i in range(count)]
    bits = 4 if len(mono) >= target_rate else 16
    if bits == 4:
        predictor = mono[0] if mono else 0
        index = 0
        codes = []
        for sample in mono[1:]:
            step = IMA_STEP[index]
            delta = sample - predictor
            code = 8 if delta < 0 else 0
            delta = abs(delta)
            diff = step >> 3
            if delta >= step: code |= 4; delta -= step; diff += step
            if delta >= step >> 1: code |= 2; delta -= step >> 1; diff += step >> 1
            if delta >= step >> 2: code |= 1; diff += step >> 2
            predictor += -diff if code & 8 else diff
            predictor = max(-32768, min(32767, predictor))
            index = max(0, min(88, index + IMA_INDEX[code]))
            codes.append(code)
        packed = bytearray(struct.pack("<hBB", mono[0] if mono else 0, 0, 0))
        for i in range(0, len(codes), 2):
            packed.append(codes[i] | ((codes[i + 1] if i + 1 < len(codes) else 0) << 4))
        payload = bytes(packed)
    else:
        payload = struct.pack(f"<{len(mono)}h", *mono)
    destination.write_bytes(SOUND_HEADER.pack(b"MSN1", target_rate, 1, bits,
                                               len(mono), zlib.crc32(payload)) + payload)
    return {"file": destination.name,
            "type": "audio_ima_adpcm" if bits == 4 else "audio_pcm16",
            "bits": bits, "bytes": destination.stat().st_size,
            "samples": len(mono), "rate": target_rate}


def _source_file(root: Path, value: str) -> Path:
    path = (root / value).resolve()
    try:
        path.relative_to(root.resolve())
    except ValueError as error:
        raise ValueError(f"asset source escapes source directory: {value}") from error
    if not path.is_file():
        raise ValueError(f"asset source does not exist: {value}")
    return path


def _output_file(root: Path, value: str, suffix: str) -> Path:
    if Path(value).name != value or not value.endswith(suffix):
        raise ValueError(f"asset output must be a {suffix} filename: {value}")
    return root / value


def compile_assets(source: Path, output: Path, manifest_file: Path,
                   limit: int = 1024 * 1024) -> dict:
    """Compile one versioned project manifest into runtime assets."""
    manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
    if manifest.get("schema") != "mosaico-game-assets/v1":
        raise ValueError("unsupported game asset manifest schema")
    output.mkdir(parents=True, exist_ok=True)
    for stale in output.iterdir():
        if stale.is_file() and stale.suffix in {".atlas", ".map", ".sound"}:
            stale.unlink()
    report: list[dict] = []
    identifiers: set[str] = set()
    animations: list[dict] = []

    for item in manifest.get("atlases", []):
        destination = _output_file(output, str(item["output"]), ".atlas")
        if item.get("generator") == "terrain":
            report.append(write_terrain_atlas(destination))
            identifiers.update(("tile_grass", "tile_path", "tile_build"))
            continue
        config_file = _source_file(source, str(item["config"]))
        config = json.loads(config_file.read_text(encoding="utf-8"))
        image = _source_file(source, str(item.get("source", config["image"])))
        report.append(write_atlas(image, config, destination))
        identifiers.update(str(frame["name"]) for frame in config["frames"])
        animations.extend(config.get("animations", []))

    for item in manifest.get("maps", []):
        source_map = _source_file(source, str(item["source"]))
        destination = _output_file(output, str(item["output"]), ".map")
        report.append(write_tilemap(source_map, destination))

    for item in manifest.get("sounds", []):
        pattern = str(item["source"])
        matches = sorted(source.glob(pattern))
        if not matches:
            raise ValueError(f"sound source pattern matched no files: {pattern}")
        for wav in matches:
            _source_file(source, str(wav.relative_to(source)))
            output_name = str(item.get("output", f"{wav.stem}.sound"))
            if len(matches) > 1 and "output" in item:
                raise ValueError("sound output cannot be fixed for a multi-file pattern")
            report.append(write_sound(wav, _output_file(output, output_name, ".sound")))

    identifiers.update(path.name for path in output.iterdir()
                       if path.suffix in {".atlas", ".map", ".sound"})
    write_asset_ids(output / "assets_ids.h", identifiers, animations)
    total = sum(item["bytes"] for item in report)
    if total > limit:
        raise ValueError(f"asset payload {total} exceeds limit {limit}")
    summary = {"schema": "mosaico-assets-report/v1", "total_bytes": total,
               "limit_bytes": limit, "files": report}
    encoded = json.dumps(summary, indent=2, sort_keys=True) + "\n"
    (output / "assets-report.json").write_text(encoded, encoding="utf-8")
    digest = hashlib.sha256()
    for path in sorted(output.iterdir()):
        if path.name not in {"assets-report.json", "assets.sha256"}:
            digest.update(path.name.encode() + b"\0" + path.read_bytes())
    (output / "assets.sha256").write_text(digest.hexdigest() + "\n", encoding="ascii")
    return summary


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--limit", type=int, default=1024 * 1024)
    args = parser.parse_args()
    manifest_file = args.manifest or args.source / "game_assets.json"
    summary = compile_assets(args.source, args.output, manifest_file, args.limit)
    encoded = json.dumps(summary, indent=2, sort_keys=True) + "\n"
    print(encoded, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
